# This workflow bumps datadog-ci in the CI integrations

name: Bump datadog-ci in CI integrations

on:
  workflow_dispatch:

jobs:
  bump-ci-integrations:
    strategy:
      fail-fast: false
      matrix:
        integration:
          # https://github.com/test-org-drarig/test-github-action
          - test-github-action

    name: Bump datadog-ci in integration
    runs-on: ubuntu-latest

    steps:
      - name: Get GitHub App token
        id: get-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.RELEASE_AUTOMATION_GITHUB_APP_ID }}
          private_key: ${{ secrets.RELEASE_AUTOMATION_GITHUB_APP_PRIVATE_KEY }}
          repository: test-org-drarig/test-github-action
      - name: Create bump datadog-ci PR
        uses: actions/github-script@v6
        with:
          # github-token: ${{ secrets.TEST_SECRET }}
          github-token: ${{ steps.get-token.outputs.token }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: '${{ matrix.integration }}',
              workflow_id: 'bump-datadog-ci.yml',
              ref: 'main',
            });
